using SimpleJigsaw;
using UnityEditor;
using UnityEngine;

/// <summary>
/// Editor utility that creates or refreshes the JigsawDemo ScriptableObject assets.
/// The scene itself (Assets/Scenes/JigsawDemo.unity) is pre-authored as YAML and does
/// not need to be regenerated by this script.
///
/// Run via: Tools/Setup/Create Jigsaw Demo Assets
/// </summary>
public static class JigsawDemoSetup
{
    private const string DemoDir         = "Assets/JigsawDemo";
    private const string GridConfigPath  = "Assets/JigsawDemo/DemoGridConfig.asset";
    private const string RenderConfigPath = "Assets/JigsawDemo/DemoPieceRenderConfig.asset";

    // ClassicKnobProfile lives in the package — reference by UPM path
    private const string KnobProfilePath =
        "Packages/com.simple-magic-studios.simple-jigsaw/Runtime/Configs/ClassicKnobProfile.asset";

    [MenuItem("Tools/Setup/Create Jigsaw Demo Assets")]
    public static void CreateJigsawDemoAssets()
    {
        // --- 1. Ensure output directory exists ---
        if (!System.IO.Directory.Exists(DemoDir))
        {
            System.IO.Directory.CreateDirectory(DemoDir);
            AssetDatabase.Refresh();
        }

        // --- 2. Load the ClassicKnob edge profile from the package ---
        var knobProfile = AssetDatabase.LoadAssetAtPath<EdgeProfileConfig>(KnobProfilePath);
        if (knobProfile == null)
        {
            Debug.LogError(
                $"[JigsawDemoSetup] Could not load ClassicKnobProfile from: {KnobProfilePath}\n" +
                "Make sure the simple-jigsaw package is registered and Unity has finished importing.");
            return;
        }

        // --- 3. Create / update DemoGridConfig ---
        var gridConfig = AssetDatabase.LoadAssetAtPath<GridLayoutConfig>(GridConfigPath);
        if (gridConfig == null)
        {
            gridConfig = ScriptableObject.CreateInstance<GridLayoutConfig>();
            AssetDatabase.CreateAsset(gridConfig, GridConfigPath);
        }

        gridConfig.Rows           = 4;
        gridConfig.Columns        = 4;
        gridConfig.EdgeProfile    = knobProfile;
        gridConfig.PieceThickness = 0.05f;
        EditorUtility.SetDirty(gridConfig);

        // --- 4. Create / update DemoPieceRenderConfig ---
        var renderConfig = AssetDatabase.LoadAssetAtPath<PieceRenderConfig>(RenderConfigPath);
        if (renderConfig == null)
        {
            renderConfig = ScriptableObject.CreateInstance<PieceRenderConfig>();
            AssetDatabase.CreateAsset(renderConfig, RenderConfigPath);
        }

        renderConfig.PieceShader      = Shader.Find("SimpleJigsaw/PuzzlePiece");
        renderConfig.PieceThickness   = 0.05f;
        renderConfig.EdgeSubdivisions = 20;
        renderConfig.OutlineEnabled   = true;
        renderConfig.OutlineColor     = Color.white;
        renderConfig.OutlineWidth     = 3f;
        EditorUtility.SetDirty(renderConfig);

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        Debug.Log(
            "[JigsawDemoSetup] Assets created/updated.\n" +
            $"  GridConfig:   {GridConfigPath}\n" +
            $"  RenderConfig: {RenderConfigPath}\n" +
            "Open Assets/Scenes/JigsawDemo.unity and press Play.");
    }
}
